---
# vars file for workernodes
containerd_url: https://raw.githubusercontent.com/lerndevops/labs/master/scripts/installContainerd.sh
component_url: https://raw.githubusercontent.com/lerndevops/labs/master/scripts/installK8S.sh